### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by AhmedHashish123** [BrightGu/MediumVC#1]
Hello, when I try to run the inference code, I get the following error:
File "Any2Any/infer/infer.py", line 11, in <module>
    from Any2Any import util
ModuleNotFoundError: No module named 'Any2Any'

I get this error when running on Google colab and locally on Windows. I believe this means that the code doesn't recognize Any2Any folder as a module which should be solved when __init__.py exists in the directory. But unfortunately, it still gives an error even when __init__.py exists.

**Comment by GlitteringAu** [comment]
Hello,I have the same problem when running on Linux.And I want to know if the  **test_wav_dir**   _'Test Samples could be organized  as "wav22050/$figure$/*.wav".'_  in `Any2Any/infer/infer_config.yaml` is the whole dataset?

**Comment by BrightGu** [comment]
> Hello,I have the same problem when running on Linux.And I want to know if the **test_wav_dir** _'Test Samples could be organized as "wav22050/$figure$/*.wav".'_ in `Any2Any/infer/infer_config.yaml` is the whole dataset?

The test_wav_dir can be organized as:
test_wav_dir/
	figure1/
		1.wav
		2.wav
	figure2/
		12.wav
		28.wav
The method "get_infer_dataset_filelist" in meldataset.py will randomly select source and target speeches. If you want to specify the source and target speeches, you could refactor the method.

**Comment by BrightGu** [comment]
> Hello, when I try to run the inference code, I get the following error: File "Any2Any/infer/infer.py", line 11, in from Any2Any import util ModuleNotFoundError: No module named 'Any2Any'
> 
> I get this error when running on Google colab and locally on Windows. I believe this means that the code doesn't recognize Any2Any folder as a module which should be solved when **init**.py exists in the directory. But unfortunately, it still gives an error even when **init**.py exists.
Try this one?
import sys
sys.path.append("your project_dir")

**Comment by GlitteringAu** [comment]
> > Hello,I have the same problem when running on Linux.And I want to know if the **test_wav_dir** _'Test Samples could be organized as "wav22050/$figure$/*.wav".'_ in `Any2Any/infer/infer_config.yaml` is the whole dataset?
> 
> The test_wav_dir can be organized as: test_wav_dir/ figure1/ 1.wav 2.wav figure2/ 12.wav 28.wav The method "get_infer_dataset_filelist" in meldataset.py will randomly select source and target speeches. If you want to specify the source and target speeches, you could refactor the method.

OK，Thank you for your timely response，I will try more to make it.

**Comment by GlitteringAu** [comment]
> > Hello, when I try to run the inference code, I get the following error: File "Any2Any/infer/infer.py", line 11, in from Any2Any import util ModuleNotFoundError: No module named 'Any2Any'
> > I get this error when running on Google colab and locally on Windows. I believe this means that the code doesn't recognize Any2Any folder as a module which should be solved when **init**.py exists in the directory. But unfortunately, it still gives an error even when **init**.py exists.
> > Try this one?
> > import sys
> > sys.path.append("your project_dir")

When I run it with pycharm, it does not seems to be to report errors like this.

**Comment by AhmedHashish123** [comment]
> > > Hello, when I try to run the inference code, I get the following error: File "Any2Any/infer/infer.py", line 11, in from Any2Any import util ModuleNotFoundError: No module named 'Any2Any'
> > > I get this error when running on Google colab and locally on Windows. I believe this means that the code doesn't recognize Any2Any folder as a module which should be solved when **init**.py exists in the directory. But unfortunately, it still gives an error even when **init**.py exists.
> > > Try this one?
> > > import sys
> > > sys.path.append("your project_dir")
> 
> When I run it with pycharm, it does not seems to be to report errors like this.

I found the solution, simply run infer.py like this: "python -m Any2Any.infer.infer"
